# Assignment 1.1 - Pandas Data Analysis Practice

*This assignment is a part of the project ["Customer Churn Analysis: From Data To Strategy"]*

In this assignment, you'll get to practice some of the concepts and skills covered in pandas.

As you go through this notebook, you will find a **???** in certain places. To complete this assignment, you must replace all the **???** with appropriate values, expressions or statements to ensure that the notebook runs properly end-to-end.

Some things to keep in mind:

* Do not change variable names, delete cells or disturb other existing code. It may cause problems during evaluation.
* In some cases, you may need to add some code cells or new statements before or after the line of code containing the **???**.
* Questions marked **(Optional)** will not be considered for evaluation, and can be skipped. They are for your learning.


If you are stuck, you can ask for help on the Whatsapp group. Please do not use **ChatGPT or any other LLM to get solutions to the questions.**


Deadline : **22 May, 11:59 pm**

In [45]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [46]:
import pandas as pd
import numpy as np

In this assignment, we're going to analyze an operate on data from a CSV file. Let's begin by downloading the CSV file.

Let's load the data from the CSV file into a Pandas data frame.

In [47]:
countries_df = pd.read_csv('/content/drive/MyDrive/countries.csv')

In [48]:
countries_df

,location,continent,population,life_expectancy,hospital_beds_per_thousand,gdp_per_capita
0,Afghanistan,Asia,38928341.0,64.83,0.50,1803.987
1,Albania,Europe,2877800.0,78.57,2.89,11803.431
2,Algeria,Africa,43851043.0,76.88,1.90,13913.839
3,Andorra,Europe,77265.0,83.73,NaN,NaN
4,Angola,Africa,32866268.0,61.15,NaN,5819.495
...,...,...,...,...,...,...
205,Vietnam,Asia,97338583.0,75.40,2.60,6171.884
206,Western Sahara,Africa,597330.0,70.26,NaN,NaN
207,Yemen,Asia,29825968.0,66.12,0.70,1479.147
208,Zambia,Africa,18383956.0,63.89,2.00,3689.251
209,Zimbabwe,Africa,14862927.0,61.49,1.70,1899.775

**Q1: How many countries does the dataframe contain?**

Hint: Use the `.shape` method.

In [49]:
num_countries = countries_df.shape
num_countries[0]

210

In [50]:
print('There are {} countries in the dataset'.format(num_countries[0]))

There are 210 countries in the dataset

**Q2: Retrieve a list of continents from the dataframe?**

*Hint: Use the `.unique` method of a series.*

In [51]:
continents = countries_df['continent'].unique()

In [52]:
continents

array(['Asia', 'Europe', 'Africa', 'North America', 'South America',
       'Oceania'], dtype=object)

**Q3: What is the total population of all the countries listed in this dataset?**

In [53]:
total_population = countries_df['population'].sum()

In [54]:
print('The total population is {}.'.format(int(total_population)))

The total population is 7757980095.

**Q: (Optional) What is the overall life expectancy across in the world?**

*Hint: You'll need to take a weighted average of life expectancy using populations as weights.*

In [55]:
countries_df['total_life']=countries_df['population']*countries_df['life_expectancy']
overall_life_expectancy=(countries_df['total_life'].sum())/total_population

In [56]:
print('The overall life expectancy is {}.'.format(float(overall_life_expectancy)))

The overall life expectancy is 72.72165193409664.

**Q4: Create a dataframe containing 10 countries with the highest population.**

*Hint: Chain the `sort_values` and `head` methods.*

In [57]:
most_populous_df = countries_df.sort_values('population',ascending=False)

In [89]:
most_populous_df.head(10)

,location,continent,population,life_expectancy,hospital_beds_per_thousand,gdp_per_capita,total_life
41,China,Asia,1.439324e+09,76.91,4.34,15308.712,1.106984e+11
90,India,Asia,1.380004e+09,69.66,0.53,6426.674,9.613111e+10
199,United States,North America,3.310026e+08,78.86,2.77,54225.446,2.610287e+10
91,Indonesia,Asia,2.735236e+08,71.72,1.04,11188.744,1.961711e+10
145,Pakistan,Asia,2.208923e+08,67.27,0.60,5034.708,1.485943e+10
27,Brazil,South America,2.125594e+08,75.88,2.20,14103.452,1.612901e+10
141,Nigeria,Africa,2.061396e+08,54.69,NaN,5338.454,1.127377e+10
15,Bangladesh,Asia,1.646894e+08,72.59,0.80,3523.984,1.195480e+10
157,Russia,Europe,1.459345e+08,72.58,8.05,24765.954,1.059192e+10
125,Mexico,North America,1.289328e+08,75.05,1.38,17336.469,9.676403e+09

**Q5: Add a new column in `countries_df` to record the overall GDP per country (product of population & per capita GDP).**

In [59]:
countries_df['gdp'] = countries_df['population']*countries_df['gdp_per_capita']

In [90]:
countries_df

,location,continent,population,life_expectancy,hospital_beds_per_thousand,gdp_per_capita,total_life,gdp
0,Afghanistan,Asia,38928341.0,64.83,0.50,1803.987,2.523724e+09,7.022622e+10
1,Albania,Europe,2877800.0,78.57,2.89,11803.431,2.261087e+08,3.396791e+10
2,Algeria,Africa,43851043.0,76.88,1.90,13913.839,3.371268e+09,6.101364e+11
3,Andorra,Europe,77265.0,83.73,NaN,NaN,6.469398e+06,NaN
4,Angola,Africa,32866268.0,61.15,NaN,5819.495,2.009772e+09,1.912651e+11
...,...,...,...,...,...,...,...,...
205,Vietnam,Asia,97338583.0,75.40,2.60,6171.884,7.339329e+09,6.007624e+11
206,Western Sahara,Africa,597330.0,70.26,NaN,NaN,4.196841e+07,NaN
207,Yemen,Asia,29825968.0,66.12,0.70,1479.147,1.972093e+09,4.411699e+10
208,Zambia,Africa,18383956.0,63.89,2.00,3689.251,1.174551e+09,6.782303e+10
209,Zimbabwe,Africa,14862927.0,61.49,1.70,1899.775,9.139214e+08,2.823622e+10

**Q: (Optional) Create a dataframe containing 10 countries with the lowest GDP per capita, among the counties with population greater than 100 million.**

In [61]:
filt=countries_df['population'] >100000000
new_df=countries_df[filt]

In [91]:
new_df.sort_values('gdp_per_capita',ascending=True).head(10)

,location,continent,population,life_expectancy,hospital_beds_per_thousand,gdp_per_capita,total_life,gdp
63,Ethiopia,Africa,1.149636e+08,66.60,0.30,1729.927,7.656575e+09,1.988786e+11
15,Bangladesh,Asia,1.646894e+08,72.59,0.80,3523.984,1.195480e+10,5.803628e+11
145,Pakistan,Asia,2.208923e+08,67.27,0.60,5034.708,1.485943e+10,1.112128e+12
141,Nigeria,Africa,2.061396e+08,54.69,NaN,5338.454,1.127377e+10,1.100467e+12
90,India,Asia,1.380004e+09,69.66,0.53,6426.674,9.613111e+10,8.868838e+12
151,Philippines,Asia,1.095811e+08,71.23,1.00,7599.188,7.805461e+09,8.327273e+11
58,Egypt,Africa,1.023344e+08,71.99,1.60,10550.206,7.367054e+09,1.079649e+12
91,Indonesia,Asia,2.735236e+08,71.72,1.04,11188.744,1.961711e+10,3.060386e+12
27,Brazil,South America,2.125594e+08,75.88,2.20,14103.452,1.612901e+10,2.997821e+12
41,China,Asia,1.439324e+09,76.91,4.34,15308.712,1.106984e+11,2.203419e+13

**Q6: Create a data frame that counts the number countries in each continent?**

*Hint: Use `groupby`, select the `location` column and aggregate using `count`.*

In [63]:
country_counts_df = countries_df.groupby('continent')
sorted=[]
for continent in continents :
  num=country_counts_df.get_group(continent).shape[0]
  sorted.append([continent,num])

In [92]:
country_count=pd.DataFrame(sorted,columns=['Continents','No_of_countries'])
country_count

      Continents  No_of_countries
0           Asia               47
1         Europe               51
2         Africa               55
3  North America               36
4  South America               13
5        Oceania                8

**Q7: Create a data frame showing the total population of each continent.**

*Hint: Use `groupby`, select the population column and aggregate using `sum`.*

In [65]:

continent_populations_df = countries_df.groupby('continent')

In [93]:
continent_populations_df['population'].sum()

continent
Africa           1.339424e+09
Asia             4.607388e+09
Europe           7.485062e+08
North America    5.912425e+08
Oceania          4.095832e+07
South America    4.304611e+08
Name: population, dtype: float64

Let's download another CSV file containing overall Covid-19 stats for various countires, and read the data into another Pandas data frame.

In [67]:
covid_data_df = pd.read_csv('/content/drive/MyDrive/covid-countries-data.csv')

In [94]:
covid_data_df

           location  total_cases  total_deaths  total_tests
0       Afghanistan      38243.0        1409.0          NaN
1           Albania       9728.0         296.0          NaN
2           Algeria      45158.0        1525.0          NaN
3           Andorra       1199.0          53.0          NaN
4            Angola       2729.0         109.0          NaN
..              ...          ...           ...          ...
207  Western Sahara        766.0           1.0          NaN
208           World   26059065.0      863535.0          NaN
209           Yemen       1976.0         571.0          NaN
210          Zambia      12415.0         292.0          NaN
211        Zimbabwe       6638.0         206.0      97272.0

[212 rows x 4 columns]

**Q8: Count the number of countries for which the `total_tests` data is missing.**

*Hint: Use the `.isna` method.*

In [69]:
total_tests_missing =covid_data_df['total_tests'].isna().sum()
total_tests_missing

122

In [70]:
print("The data for total tests is missing for {} countries.".format(int(total_tests_missing)))

The data for total tests is missing for 122 countries.

Let's merge the two data frames, and compute some more metrics.

**Q9: Merge `countries_df` with `covid_data_df` on the `location` column.**

*Hint: Use the `.merge` method on `countries_df`.

In [71]:
combined_df = pd.merge(countries_df, covid_data_df, on='location', how='outer')

In [95]:
combined_df

,location,continent,population,life_expectancy,hospital_beds_per_thousand,gdp_per_capita,total_life,gdp,total_cases,total_deaths,total_tests,tests_per_million,cases_per_million,deaths_per_million
0,Afghanistan,Asia,38928341.0,64.83,0.50,1803.987,2.523724e+09,7.022622e+10,38243.0,1409.0,NaN,NaN,982.394806,36.194710
1,Albania,Europe,2877800.0,78.57,2.89,11803.431,2.261087e+08,3.396791e+10,9728.0,296.0,NaN,NaN,3380.359997,102.856349
2,Algeria,Africa,43851043.0,76.88,1.90,13913.839,3.371268e+09,6.101364e+11,45158.0,1525.0,NaN,NaN,1029.804468,34.776824
3,Andorra,Europe,77265.0,83.73,NaN,NaN,6.469398e+06,NaN,1199.0,53.0,NaN,NaN,15518.022390,685.950948
4,Angola,Africa,32866268.0,61.15,NaN,5819.495,2.009772e+09,1.912651e+11,2729.0,109.0,NaN,NaN,83.033462,3.316470
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
207,Yemen,Asia,29825968.0,66.12,0.70,1479.147,1.972093e+09,4.411699e+10,1976.0,571.0,NaN,NaN,66.250993,19.144391
208,Zambia,Africa,18383956.0,63.89,2.00,3689.251,1.174551e+09,6.782303e+10,12415.0,292.0,NaN,NaN,675.317108,15.883415
209,Zimbabwe,Africa,14862927.0,61.49,1.70,1899.775,9.139214e+08,2.823622e+10,6638.0,206.0,97272.0,6544.605918,446.614587,13.859989
210,International,NaN,NaN,NaN,NaN,NaN,NaN,NaN,705.0,7.0,NaN,NaN,NaN,NaN
211,World,NaN,NaN,NaN,NaN,NaN,NaN,NaN,26059065.0,863535.0,NaN,NaN,NaN,NaN

**Q10: Add columns `tests_per_million`, `cases_per_million` and `deaths_per_million` into `combined_df`.**

In [73]:
combined_df['tests_per_million'] = combined_df['total_tests'] * 1e6 / combined_df['population']

In [74]:
combined_df['cases_per_million'] = combined_df['total_cases']* 1e6 / combined_df['population']

In [75]:
combined_df['deaths_per_million'] = combined_df['total_deaths']* 1e6 / combined_df['population']

In [96]:
combined_df

,location,continent,population,life_expectancy,hospital_beds_per_thousand,gdp_per_capita,total_life,gdp,total_cases,total_deaths,total_tests,tests_per_million,cases_per_million,deaths_per_million
0,Afghanistan,Asia,38928341.0,64.83,0.50,1803.987,2.523724e+09,7.022622e+10,38243.0,1409.0,NaN,NaN,982.394806,36.194710
1,Albania,Europe,2877800.0,78.57,2.89,11803.431,2.261087e+08,3.396791e+10,9728.0,296.0,NaN,NaN,3380.359997,102.856349
2,Algeria,Africa,43851043.0,76.88,1.90,13913.839,3.371268e+09,6.101364e+11,45158.0,1525.0,NaN,NaN,1029.804468,34.776824
3,Andorra,Europe,77265.0,83.73,NaN,NaN,6.469398e+06,NaN,1199.0,53.0,NaN,NaN,15518.022390,685.950948
4,Angola,Africa,32866268.0,61.15,NaN,5819.495,2.009772e+09,1.912651e+11,2729.0,109.0,NaN,NaN,83.033462,3.316470
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
207,Yemen,Asia,29825968.0,66.12,0.70,1479.147,1.972093e+09,4.411699e+10,1976.0,571.0,NaN,NaN,66.250993,19.144391
208,Zambia,Africa,18383956.0,63.89,2.00,3689.251,1.174551e+09,6.782303e+10,12415.0,292.0,NaN,NaN,675.317108,15.883415
209,Zimbabwe,Africa,14862927.0,61.49,1.70,1899.775,9.139214e+08,2.823622e+10,6638.0,206.0,97272.0,6544.605918,446.614587,13.859989
210,International,NaN,NaN,NaN,NaN,NaN,NaN,NaN,705.0,7.0,NaN,NaN,NaN,NaN
211,World,NaN,NaN,NaN,NaN,NaN,NaN,NaN,26059065.0,863535.0,NaN,NaN,NaN,NaN

**Q11: Create a dataframe with 10 countires that have highest number of tests per million people.**

In [77]:
highest_tests_df = combined_df.sort_values('tests_per_million',ascending=False)

In [97]:
highest_tests_df.head(10)

,location,continent,population,life_expectancy,hospital_beds_per_thousand,gdp_per_capita,total_life,gdp,total_cases,total_deaths,total_tests,tests_per_million,cases_per_million,deaths_per_million
197,United Arab Emirates,Asia,9890400.0,77.97,1.200,67293.483,7.711545e+08,6.655595e+11,71540.0,387.0,7177430.0,725696.635121,7233.276713,39.128852
14,Bahrain,Asia,1701583.0,77.29,2.000,43290.705,1.315154e+08,7.366273e+10,52440.0,190.0,1118837.0,657527.137965,30818.361490,111.660730
115,Luxembourg,Europe,625976.0,82.25,4.510,94277.965,5.148653e+07,5.901574e+10,7928.0,124.0,385820.0,616349.508607,12665.022301,198.090662
122,Malta,Europe,441539.0,82.53,4.485,36513.323,3.644021e+07,1.612206e+10,1931.0,13.0,188539.0,427004.183096,4373.339614,29.442473
53,Denmark,Europe,5792203.0,80.90,2.500,46682.515,4.685892e+08,2.703946e+11,17195.0,626.0,2447911.0,422621.755488,2968.645954,108.076323
96,Israel,Asia,8655541.0,82.97,2.990,33132.320,7.181502e+08,2.867782e+11,122539.0,969.0,2353984.0,271962.665303,14157.289533,111.951408
89,Iceland,Europe,341250.0,82.99,2.910,46482.958,2.832034e+07,1.586231e+10,2121.0,10.0,88829.0,260304.761905,6215.384615,29.304029
157,Russia,Europe,145934460.0,72.58,8.050,24765.954,1.059192e+10,3.614206e+12,1005000.0,17414.0,37176827.0,254750.159763,6886.653091,119.327539
199,United States,North America,331002647.0,78.86,2.770,54225.446,2.610287e+10,1.794877e+13,6114406.0,185744.0,83898416.0,253467.507769,18472.377957,561.155633
10,Australia,Oceania,25499881.0,83.44,3.840,44648.710,2.127710e+09,1.138537e+12,25923.0,663.0,6255797.0,245326.517406,1016.592979,26.000121

**Q12: Create a dataframe with 10 countires that have highest number of positive cases per million people.**

In [79]:
highest_cases_df =combined_df.sort_values('cases_per_million',ascending=False)

In [98]:
highest_cases_df.head(10)

,location,continent,population,life_expectancy,hospital_beds_per_thousand,gdp_per_capita,total_life,gdp,total_cases,total_deaths,total_tests,tests_per_million,cases_per_million,deaths_per_million
155,Qatar,Asia,2881060.0,80.23,1.20,116935.600,2.311474e+08,3.368985e+11,119206.0,199.0,634745.0,220316.480740,41375.743650,69.071800
14,Bahrain,Asia,1701583.0,77.29,2.00,43290.705,1.315154e+08,7.366273e+10,52440.0,190.0,1118837.0,657527.137965,30818.361490,111.660730
147,Panama,North America,4314768.0,78.51,2.30,22267.037,3.387524e+08,9.607710e+10,94084.0,2030.0,336345.0,77952.047480,21805.112117,470.477208
40,Chile,South America,19116209.0,80.18,2.11,22767.037,1.532738e+09,4.352194e+11,414739.0,11344.0,2458762.0,128621.841287,21695.671982,593.423100
162,San Marino,Europe,33938.0,84.97,3.80,56861.470,2.883712e+06,1.929765e+09,735.0,42.0,NaN,NaN,21657.139490,1237.550828
9,Aruba,North America,106766.0,76.29,NaN,35973.781,8.145178e+06,3.840777e+09,2211.0,12.0,NaN,NaN,20708.839893,112.395332
105,Kuwait,Asia,4270563.0,75.49,2.00,65530.537,3.223848e+08,2.798523e+11,86478.0,535.0,621616.0,145558.325682,20249.789079,125.276222
150,Peru,South America,32971846.0,76.74,1.60,12236.706,2.530259e+09,4.034668e+11,663437.0,29259.0,584232.0,17719.117092,20121.318048,887.393445
27,Brazil,South America,212559409.0,75.88,2.20,14103.452,1.612901e+10,2.997821e+12,3997865.0,123780.0,4797948.0,22572.268255,18808.224105,582.331314
199,United States,North America,331002647.0,78.86,2.77,54225.446,2.610287e+10,1.794877e+13,6114406.0,185744.0,83898416.0,253467.507769,18472.377957,561.155633

**Q13: Create a dataframe with 10 countires that have highest number of deaths cases per million people?**

In [81]:
highest_deaths_df = combined_df.sort_values('deaths_per_million',ascending=False)

In [99]:
highest_deaths_df.head(10)

,location,continent,population,life_expectancy,hospital_beds_per_thousand,gdp_per_capita,total_life,gdp,total_cases,total_deaths,total_tests,tests_per_million,cases_per_million,deaths_per_million
162,San Marino,Europe,33938.0,84.97,3.80,56861.470,2.883712e+06,1.929765e+09,735.0,42.0,NaN,NaN,21657.139490,1237.550828
150,Peru,South America,32971846.0,76.74,1.60,12236.706,2.530259e+09,4.034668e+11,663437.0,29259.0,584232.0,17719.117092,20121.318048,887.393445
18,Belgium,Europe,11589616.0,81.63,5.64,42658.576,9.460604e+08,4.943965e+11,85817.0,9898.0,2281853.0,196887.713967,7404.645676,854.040375
3,Andorra,Europe,77265.0,83.73,NaN,NaN,6.469398e+06,NaN,1199.0,53.0,NaN,NaN,15518.022390,685.950948
177,Spain,Europe,46754783.0,83.56,2.97,34272.360,3.906830e+09,1.602397e+12,479554.0,29194.0,6416533.0,137238.001939,10256.790198,624.406705
198,United Kingdom,Europe,67886004.0,81.32,2.54,39753.244,5.520490e+09,2.698689e+12,338676.0,41514.0,13447568.0,198090.434075,4988.892850,611.525168
40,Chile,South America,19116209.0,80.18,2.11,22767.037,1.532738e+09,4.352194e+11,414739.0,11344.0,2458762.0,128621.841287,21695.671982,593.423100
97,Italy,Europe,60461828.0,83.51,3.18,35220.084,5.049167e+09,2.129471e+12,271515.0,35497.0,5214766.0,86248.897403,4490.684602,587.097697
27,Brazil,South America,212559409.0,75.88,2.20,14103.452,1.612901e+10,2.997821e+12,3997865.0,123780.0,4797948.0,22572.268255,18808.224105,582.331314
182,Sweden,Europe,10099270.0,82.80,2.22,46949.283,8.362196e+08,4.741535e+11,84532.0,5820.0,NaN,NaN,8370.109919,576.279276

**(Optional) Q: Count number of countries that feature in both the lists of "highest number of tests per million" and "highest number of cases per million".**

In [100]:
new1=highest_cases_df.head(10)

new1

,location,continent,population,life_expectancy,hospital_beds_per_thousand,gdp_per_capita,total_life,gdp,total_cases,total_deaths,total_tests,tests_per_million,cases_per_million,deaths_per_million
155,Qatar,Asia,2881060.0,80.23,1.20,116935.600,2.311474e+08,3.368985e+11,119206.0,199.0,634745.0,220316.480740,41375.743650,69.071800
14,Bahrain,Asia,1701583.0,77.29,2.00,43290.705,1.315154e+08,7.366273e+10,52440.0,190.0,1118837.0,657527.137965,30818.361490,111.660730
147,Panama,North America,4314768.0,78.51,2.30,22267.037,3.387524e+08,9.607710e+10,94084.0,2030.0,336345.0,77952.047480,21805.112117,470.477208
40,Chile,South America,19116209.0,80.18,2.11,22767.037,1.532738e+09,4.352194e+11,414739.0,11344.0,2458762.0,128621.841287,21695.671982,593.423100
162,San Marino,Europe,33938.0,84.97,3.80,56861.470,2.883712e+06,1.929765e+09,735.0,42.0,NaN,NaN,21657.139490,1237.550828
9,Aruba,North America,106766.0,76.29,NaN,35973.781,8.145178e+06,3.840777e+09,2211.0,12.0,NaN,NaN,20708.839893,112.395332
105,Kuwait,Asia,4270563.0,75.49,2.00,65530.537,3.223848e+08,2.798523e+11,86478.0,535.0,621616.0,145558.325682,20249.789079,125.276222
150,Peru,South America,32971846.0,76.74,1.60,12236.706,2.530259e+09,4.034668e+11,663437.0,29259.0,584232.0,17719.117092,20121.318048,887.393445
27,Brazil,South America,212559409.0,75.88,2.20,14103.452,1.612901e+10,2.997821e+12,3997865.0,123780.0,4797948.0,22572.268255,18808.224105,582.331314
199,United States,North America,331002647.0,78.86,2.77,54225.446,2.610287e+10,1.794877e+13,6114406.0,185744.0,83898416.0,253467.507769,18472.377957,561.155633

In [101]:
new2=highest_tests_df.head(10)
new2

,location,continent,population,life_expectancy,hospital_beds_per_thousand,gdp_per_capita,total_life,gdp,total_cases,total_deaths,total_tests,tests_per_million,cases_per_million,deaths_per_million
197,United Arab Emirates,Asia,9890400.0,77.97,1.200,67293.483,7.711545e+08,6.655595e+11,71540.0,387.0,7177430.0,725696.635121,7233.276713,39.128852
14,Bahrain,Asia,1701583.0,77.29,2.000,43290.705,1.315154e+08,7.366273e+10,52440.0,190.0,1118837.0,657527.137965,30818.361490,111.660730
115,Luxembourg,Europe,625976.0,82.25,4.510,94277.965,5.148653e+07,5.901574e+10,7928.0,124.0,385820.0,616349.508607,12665.022301,198.090662
122,Malta,Europe,441539.0,82.53,4.485,36513.323,3.644021e+07,1.612206e+10,1931.0,13.0,188539.0,427004.183096,4373.339614,29.442473
53,Denmark,Europe,5792203.0,80.90,2.500,46682.515,4.685892e+08,2.703946e+11,17195.0,626.0,2447911.0,422621.755488,2968.645954,108.076323
96,Israel,Asia,8655541.0,82.97,2.990,33132.320,7.181502e+08,2.867782e+11,122539.0,969.0,2353984.0,271962.665303,14157.289533,111.951408
89,Iceland,Europe,341250.0,82.99,2.910,46482.958,2.832034e+07,1.586231e+10,2121.0,10.0,88829.0,260304.761905,6215.384615,29.304029
157,Russia,Europe,145934460.0,72.58,8.050,24765.954,1.059192e+10,3.614206e+12,1005000.0,17414.0,37176827.0,254750.159763,6886.653091,119.327539
199,United States,North America,331002647.0,78.86,2.770,54225.446,2.610287e+10,1.794877e+13,6114406.0,185744.0,83898416.0,253467.507769,18472.377957,561.155633
10,Australia,Oceania,25499881.0,83.44,3.840,44648.710,2.127710e+09,1.138537e+12,25923.0,663.0,6255797.0,245326.517406,1016.592979,26.000121

In [102]:
filt1=pd.merge(new1, new2 , on='location', how='inner')

filt1.shape[0]

2

**(Optional) Q: Count number of countries that feature in both the lists "20 countries with lowest GDP per capita" and "20 countries with the lowest number of hospital beds per thousand population". Only consider countries with a population higher than 10 million while creating the list.**

In [103]:
filt2= combined_df['population'] > 10000000
low_gdp=combined_df[filt2].sort_values('gdp_per_capita',ascending=True).head(20)
low_gdp

,location,continent,population,life_expectancy,hospital_beds_per_thousand,gdp_per_capita,total_life,gdp,total_cases,total_deaths,total_tests,tests_per_million,cases_per_million,deaths_per_million
32,Burundi,Africa,11890781.0,61.58,0.8,702.225,7.322343e+08,8.350004e+09,448.0,1.0,NaN,NaN,37.676247,0.084099
52,Democratic Republic of Congo,Africa,89561404.0,60.68,NaN,808.133,5.434586e+09,7.237753e+10,10113.0,258.0,NaN,NaN,112.916944,2.880705
140,Niger,Africa,24206636.0,62.42,0.3,926.000,1.510978e+09,2.241534e+10,1177.0,69.0,NaN,NaN,48.623030,2.850458
118,Malawi,Africa,19129955.0,64.26,1.3,1095.042,1.229291e+09,2.094810e+10,5579.0,175.0,NaN,NaN,291.636860,9.147957
132,Mozambique,Africa,31255435.0,60.85,0.7,1136.103,1.901893e+09,3.550939e+10,4117.0,25.0,NaN,NaN,131.721091,0.799861
117,Madagascar,Africa,27691019.0,67.04,0.2,1416.440,1.856406e+09,3.922267e+10,15023.0,196.0,NaN,NaN,542.522469,7.078107
207,Yemen,Asia,29825968.0,66.12,0.7,1479.147,1.972093e+09,4.411699e+10,1976.0,571.0,NaN,NaN,66.250993,19.144391
176,South Sudan,Africa,11193729.0,57.85,NaN,1569.888,6.475572e+08,1.757290e+10,2532.0,47.0,NaN,NaN,226.198079,4.198780
85,Haiti,North America,11402533.0,64.00,0.7,1653.173,7.297621e+08,1.885036e+10,8258.0,206.0,NaN,NaN,724.225047,18.066161
195,Uganda,Africa,45741000.0,63.37,0.5,1697.707,2.898607e+09,7.765482e+10,3112.0,32.0,381749.0,8345.882250,68.035242,0.699591
31,Burkina Faso,Africa,20903278.0,61.58,0.4,1703.102,1.287224e+09,3.560041e+10,1378.0,55.0,NaN,NaN,65.922675,2.631166
63,Ethiopia,Africa,114963583.0,66.60,0.3,1729.927,7.656575e+09,1.988786e+11,54409.0,846.0,869430.0,7562.655732,473.271610,7.358852
39,Chad,Africa,16425859.0,54.24,NaN,1768.153,8.909386e+08,2.904343e+10,1017.0,77.0,NaN,NaN,61.914570,4.687730
0,Afghanistan,Asia,38928341.0,64.83,0.5,1803.987,2.523724e+09,7.022622e+10,38243.0,1409.0,NaN,NaN,982.394806,36.194710
158,Rwanda,Africa,12952209.0,69.02,NaN,1854.211,8.939615e+08,2.401613e+10,4218.0,17.0,393237.0,30360.612618,325.658735,1.312517
209,Zimbabwe,Africa,14862927.0,61.49,1.7,1899.775,9.139214e+08,2.823622e+10,6638.0,206.0,97272.0,6544.605918,446.614587,13.859989
82,Guinea,Africa,13132792.0,61.60,0.3,1998.926,8.089800e+08,2.625148e+10,9479.0,59.0,NaN,NaN,721.781020,4.492571
121,Mali,Africa,20250834.0,59.31,0.1,2014.306,1.201077e+09,4.079138e+10,2802.0,126.0,NaN,NaN,138.364672,6.221966
20,Benin,Africa,12123198.0,61.77,0.5,2064.236,7.488499e+08,2.502514e+10,2194.0,40.0,NaN,NaN,180.975350,3.299459
135,Nepal,Asia,29136808.0,70.78,0.3,2442.804,2.062303e+09,7.117551e+10,41649.0,251.0,705560.0,24215.418518,1429.429058,8.614533

In [104]:
low_hospital_beds=combined_df[filt2].sort_values('hospital_beds_per_thousand',ascending=True).head(20)
low_hospital_beds

,location,continent,population,life_expectancy,hospital_beds_per_thousand,gdp_per_capita,total_life,gdp,total_cases,total_deaths,total_tests,tests_per_million,cases_per_million,deaths_per_million
121,Mali,Africa,2.025083e+07,59.31,0.10,2014.306,1.201077e+09,4.079138e+10,2802.0,126.0,NaN,NaN,138.364672,6.221966
117,Madagascar,Africa,2.769102e+07,67.04,0.20,1416.440,1.856406e+09,3.922267e+10,15023.0,196.0,NaN,NaN,542.522469,7.078107
140,Niger,Africa,2.420664e+07,62.42,0.30,926.000,1.510978e+09,2.241534e+10,1177.0,69.0,NaN,NaN,48.623030,2.850458
135,Nepal,Asia,2.913681e+07,70.78,0.30,2442.804,2.062303e+09,7.117551e+10,41649.0,251.0,705560.0,24215.418518,1429.429058,8.614533
82,Guinea,Africa,1.313279e+07,61.60,0.30,1998.926,8.089800e+08,2.625148e+10,9479.0,59.0,NaN,NaN,721.781020,4.492571
63,Ethiopia,Africa,1.149636e+08,66.60,0.30,1729.927,7.656575e+09,1.988786e+11,54409.0,846.0,869430.0,7562.655732,473.271610,7.358852
31,Burkina Faso,Africa,2.090328e+07,61.58,0.40,1703.102,1.287224e+09,3.560041e+10,1378.0,55.0,NaN,NaN,65.922675,2.631166
195,Uganda,Africa,4.574100e+07,63.37,0.50,1697.707,2.898607e+09,7.765482e+10,3112.0,32.0,381749.0,8345.882250,68.035242,0.699591
0,Afghanistan,Asia,3.892834e+07,64.83,0.50,1803.987,2.523724e+09,7.022622e+10,38243.0,1409.0,NaN,NaN,982.394806,36.194710
20,Benin,Africa,1.212320e+07,61.77,0.50,2064.236,7.488499e+08,2.502514e+10,2194.0,40.0,NaN,NaN,180.975350,3.299459
90,India,Asia,1.380004e+09,69.66,0.53,6426.674,9.613111e+10,8.868838e+12,3853406.0,67376.0,44337201.0,32128.304433,2792.314316,48.823033
80,Guatemala,North America,1.791557e+07,74.30,0.60,7423.808,1.331127e+09,1.330017e+11,75664.0,2790.0,NaN,NaN,4223.366193,155.730488
145,Pakistan,Asia,2.208923e+08,67.27,0.60,5034.708,1.485943e+10,1.112128e+12,297014.0,6328.0,2662508.0,12053.419817,1344.609832,28.647441
85,Haiti,North America,1.140253e+07,64.00,0.70,1653.173,7.297621e+08,1.885036e+10,8258.0,206.0,NaN,NaN,724.225047,18.066161
207,Yemen,Asia,2.982597e+07,66.12,0.70,1479.147,1.972093e+09,4.411699e+10,1976.0,571.0,NaN,NaN,66.250993,19.144391
187,Tanzania,Africa,5.973421e+07,65.46,0.70,2683.304,3.910202e+09,1.602851e+11,509.0,21.0,NaN,NaN,8.521080,0.351557
132,Mozambique,Africa,3.125544e+07,60.85,0.70,1136.103,1.901893e+09,3.550939e+10,4117.0,25.0,NaN,NaN,131.721091,0.799861
32,Burundi,Africa,1.189078e+07,61.58,0.80,702.225,7.322343e+08,8.350004e+09,448.0,1.0,NaN,NaN,37.676247,0.084099
33,Cambodia,Asia,1.671897e+07,69.82,0.80,3645.070,1.167319e+09,6.094182e+10,274.0,0.0,NaN,NaN,16.388568,0.000000
204,Venezuela,South America,2.843594e+07,72.06,0.80,16745.022,2.049094e+09,4.761605e+11,48883.0,398.0,NaN,NaN,1719.056759,13.996371

In [105]:
low_gdp_low_beds=pd.merge(low_gdp,low_hospital_beds,on = 'location',how='inner')
low_gdp_low_beds.shape[0]

14

## Submission

Congratulations on making it this far! You've reached the end of this assignment, and you just completed your first real-world data analysis problem. It's time to record one final version of your notebook for submission.

Make a submission here by filling the submission form: https://jovian.ai/learn/data-analysis-with-python-zero-to-pandas/assignment/assignment-3-pandas-practice

Also make sure to help others on the forum: https://jovian.ai/forum/t/assignment-3-pandas-practice/11225/2